<?php
$this->title = "Artist";
$this->headTitle($this->title);
?>
<p><button id="AddButton"> Add New Artist </button></p>
<table id="co" class="table" style="width:100%">
        <thead class="thead-dark">

                <th>ID</th>
                <th>Artist_Name</th>
                <th>Action</th>
        </thead>
</table>
<div class="modal" id="formview">
        <div id="contentmodel">
                <form class="animate" id="addeditForm" method="GET" >
                        <div class="container">
                                <h1>Artist</h1>
                                </br>
                                <div class="form-group">
                                        <input type="hidden" id="id" name="id">
                                        <label for="Artist"><b>Artist_Name</b></label>
                                        <input type="text" class="form-control" placeholder="Enter Artist" name="Artist" id="artist">
                                </div>
                                <button name="Save" class="btn btn-primary" id="Save">Save</button>
                                <button name="Cancel" data-dismiss="modal" data-target="#formview" class="btn btn-primary" id="Cancel" style="display:inline-block;">Cancel</button>
                        </div>
                </form>
        </div>
</div>
<?php echo $this->headScript()->appendFile($this->baseUrl() . '/JS/artist.js'); ?>