<?php
$this->title = "Category";
$this->headTitle($this->title);
?>
<p><button id="AddButton"> Add New Category </button></p>
<table id="co" class="table" style="width:100%">
        <thead class="thead-dark">

                <th>ID</th>
                <th>Category_Name</th>
                <th>Action</th>
        </thead>
</table>
<div class="modal" id="formview">
        <div id="contentmodel">
                <form class="animate" id="addeditForm" method="POST" action="/category/submit" enctype="multipart/form-data">
                        <div class="container">
                                <h1>Artist</h1>
                                </br>
                                <div class="form-group">
                                        <input type="hidden" id="id" name="id">
                                        <label for="category"><b>Category_Name</b></label>
                                        <input type="text" class="form-control" placeholder="Enter Category" name="Categoryname" id="category">
                                </div>
                                <input type="submit" name="Save" class="btn btn-primary" id="Save" value="Save">
                                <input type="button" name="Cancel" data-dismiss="modal" data-target="#formview" class="btn btn-primary" id="Cancel" value="Cancel" style="display:inline-block;">
                        </div>
                </form>
        </div>
</div>
<?php echo $this->headScript()->appendFile($this->baseUrl() . '/JS/category.js'); ?>