<?php
$this->title = "My Albums";
$this->headTitle($this->title);
?>
<p><button id="AddButton" data-id=""> Add New Album </button></p>
<table id="co" class="table" style="width:100%">
        <thead class="thead-dark">

                <th>ID</th>
                <th>Artist_Name</th>
                <th>Category</th>
                <th>image</th>
                <th>Action</th>
        </thead>
</table>
<div class="modal" id="formview">
        <div id="contentmodel">
                <form class="animate" id="addeditForm" method="POST">
                        <div class="container">
                                <h1>Album</h1>
                                </br>
                                <div class="form-group">
                                        <input type="hidden" id="id" name="id">
                                        <input type="hidden" id="image" name="image">
                                        <img id="img" style="height: 160px; width: 160px;">

                                        </br>
                                        <div id="filelist">Your browser doesn't have Flash, Silverlight or HTML5 support.</div>
                                        <br />

                                        <div id="container">
                                                <button id="browse" href="javascript:;">[Browse...]</button>
                                                <a id="start-upload" href="javascript:;">[Start Upload]</a>
                                        </div>
                                        <br />
                                        <pre id="console"></pre>
                                        <label for="Name"><b>Artist</b></label>
                                        <select name="Artist" class="js-example-placeholder-single js-states form-control artist" onselect="this.value;" style="width: 100%;" required>
                                                <option value="" disabled selected>Choose option</option>
                                                <?php
                                                foreach ($this->artist as $artist) {

                                                ?>
                                                        <option value="<?php echo $artist->ID; ?>"><?php echo $this->escape($artist->Artist_Name); ?></option>
                                                <?php } ?>
                                        </select>
                                </div>
                                <div class="form-group">
                                        <label for="Category"><b>Category</b></label>
                                        <select name="Category[]" class="js-example-placeholder-multiple js-states form-control category" onselect="this.value;" style="width: 100%;" multiple required>
                                                <?php
                                                foreach ($this->category as $category) {

                                                ?>
                                                        <option value="<?php echo $category->ID; ?>"><?php echo $this->escape($category->Category_Name); ?></option>
                                                <?php } ?>
                                        </select>
                                </div>
                                <button name="Save" class="btn btn-primary" id="Save">Save</button>
                                <button name="Cancel" data-dismiss="modal" data-target="#formview" class="btn btn-primary" id="Cancel" style="display:inline-block;">Cancel</button>
                        </div>
                </form>
        </div>
</div>
<?php echo $this->headScript()->appendFile($this->baseUrl() . '/JS/pluploadjs/plupload.full.min.js'); ?>
<?php echo $this->headScript()->appendFile($this->baseUrl() . '/JS/pluploadjs/moxie.js'); ?>
<?php echo $this->headScript()->appendFile($this->baseUrl() . '/JS/pluploadjs/jquery.plupload.queue/jquery.plupload.queue.min.js'); ?>
<?php echo $this->headScript()->appendFile($this->baseUrl() . '/JS/index.js'); ?>