<nav id="na" name="na" class="navbar navbar-expand-sm bg-dark navbar-dark">
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav">
            <div class="col-sm">
                <li class="nav-item">
                    <a class="nav-link" id="menu" href="/index/index">Album</button></a>
                </li>
            </div>
            <div class="col-sm">
                <li class="nav-item">
                    <a class="nav-link" href="/artist/artist" id="menu">Artist</button></a>
                </li>
            </div>
            <div class="col-sm">
                <li class="nav-item">
                    <a class="nav-link" href="/category/category" id="menu">Category</button></a>
                </li>
            </div>
        </ul>
    </div>

</nav>